### ISSUE TITLE
Problems with images

### ISSUE THREAD

**Issue by zuri10** [DeustoKom/MSGW2021-timeline#6] opened 2021-05-19 10:10 UTC
Group 4. Second line. Benot Law: Url image
7941db84e1c6290d6c7cbcaf76174d5f (514×480)

**Comment by mirenbz** [comment] 2021-05-19 11:57
Hi @zuri10 , the problem is not in the lack of file extensions, but the fact that you did not actually enter a URL there in the `mediaURL` column. 

The fragment you sent to me by email was linked to `https://s3.amazonaws.com/s3.timetoast.com/public/uploads/photo/8930263/image/7941db84e1c6290d6c7cbcaf76174d5f` (which is the actual URL that displays the image, if you check in a browser). Try using that instead, and see if it works!

You have the same problem in other lines as well, which could probably be fixed similarly.

**Comment by mirenbz** [comment] 2021-05-21 08:44
Feel free to close this issue if it is fixed!

**Closed** 2021-05-21 09:03 UTC
